### ISSUE TITLE
opensuse support for Tumbleweed is broken

### ISSUE THREAD

**Issue by twxjyg** [ros-infrastructure/rospkg#120]
my openSUSE version is [openSUSE Tumbleweed] and the /etc/SuSE-brand and /etc/SuSE-release file is not exist, so I had to touch these two files mannully.

**Comment by tfoote** [comment]
Thanks for the report. It sounds like TumbleWeed has changed how the versions can be detected. I'm assuming TumbleWeed is new as I haven't heard of it before.

The [os_detect](https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py) module has the logic for detecting the OS. A pull request to fix support for TumbleWeed would be appreciated. Since it's not officially supported we rely on community contributions to support openSUSE.

**Comment by dirk-thomas** [comment]
Addressed by #121.
