### ISSUE TITLE
RosPack('/foo/bar') should not be silently accepted

### ISSUE THREAD

**Issue by KenYN** [ros-infrastructure/rospkg#160]
If I accidentally forget to make a directory into a list when constructing `RosPack()`, calling `get_ros_paths()` goes into a very long-lasting loop over every single character in the directory path.

It would be nice if `__init__` either threw an error or silently made a single string into a list, for example:

[rospack.py line 124](https://github.com/ros-infrastructure/rospkg/blob/f187910cd7af7e34bbe1d6f386bbc27a9f2cbf01/src/rospkg/rospack.py#L124):

    if not type(ros_paths) is list:
        ros_paths = [ros_paths]

Or:

    if not type(ros_paths) is list:
        raise TypeError('Argument must be a list')

**Comment by dirk-thomas** [comment]
Catching this kind of misuse would certainly be nice.

Since existing code might pass other values to the function than lists I don't think we can require the argument to be of type `list` now. But checking that the argument is not a `str` should certainly be feasible.

Please consider to provide a pull request for this proposed improvement.

**Comment by dirk-thomas** [comment]
I will go ahead and close this since there seems to be no interest in implementing this improvement atm.
