### ISSUE TITLE
ROS2 (colcon/ament) support

### ISSUE THREAD

**Issue by max-krichenbauer** [ros-infrastructure/rospkg#174]
Hello,

Sorry if this is a stupid question, but is ``rospkg`` expected to be used with ROS2 / colcon / ament?

If so, https://github.com/ros-infrastructure/rospkg/blob/d5ad8612c47ccb014b6d06de98a4a46ace7ba31a/src/rospkg/rospack.py#L62 should not only respect ``CATKIN_IGNORE`` but also ``COLCON_IGNORE`` and ``AMENT_IGNORE``.

Maybe there are more issues, but I just happened to stumble upon this.

Thank you for your time and best regards,
Max

**Comment by dirk-thomas** [comment]
No, `rospkg` is only used for ROS 1.

**Comment by max-krichenbauer** [comment]
Thank you for the clarification!

**Comment by max-krichenbauer** [comment]
Follow-up question:

If ``rospkg`` is only compatible with ROS1 packages, it should not interpret ROS2 ``package.xml`` files as ROS1 ``package.xml`` files, correct?

To be precise:
https://github.com/ros-infrastructure/rospkg/blob/d5ad8612c47ccb014b6d06de98a4a46ace7ba31a/src/rospkg/rospack.py#L67
should be followed by a check if the ``<package>`` tag is present and if it contains ``format="2"``.

Correct?

**Comment by dirk-thomas** [comment]
No, the format attribute in the manifest has nothing to do with the major ROS version. Format 1, 2 and 3 describe three evolutions of the manifest file. All three can be used in ROS 1. ROS 2 supports all but format 1 since it has a different semantic for some dependency types which didn't make sense to support in ROS 2 (and probably shouldn't be used in ROS 1 either - but still used for backward compatibility).
