### ISSUE TITLE
On Ubuntu 16.04 Xenial, python-rospkg now depends on non-exsting python-distro

### ISSUE THREAD

**Issue by ANogin** [ros-infrastructure/rospkg#185]
```
$ docker pull ubuntu:16.04
[...]
$ docker run -it ubuntu:16.04
# echo 'deb http://packages.ros.org/ros/ubuntu xenial main'  > /etc/apt/sources.list.d/ros-latest.list
# apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
[...]
# apt-get -y update
[...]
# apt-get -y install python-rospkg-modules
[...]
The following packages have unmet dependencies:
 python-rospkg-modules : Depends: python-distro but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by mikepurvis** [comment]
Looks like it's used only conditionally with a fallback:

https://github.com/ros-infrastructure/rospkg/blob/9956e80bc8c81a42abe1da6132aa3419615359cc/src/rospkg/os_detect.py#L39-L43

So there should be logic in the `setup.py` to exclude the dependency from systems which don't have it (although perhaps only in the stdeb case, since maybe you would still want it when installing these tools in a virtualenv).

**Comment by ANogin** [comment]
> 
> 
> Looks like it's used only conditionally with a fallback:
> 
> https://github.com/ros-infrastructure/rospkg/blob/9956e80bc8c81a42abe1da6132aa3419615359cc/src/rospkg/os_detect.py#L39-L43
> 
> So there should be logic in the `setup.py` to exclude the dependency from systems which don't have it (although perhaps only in the stdeb case, since maybe you would still want it when installing these tools in a virtualenv).

That run-time logic is only helpful once you manage to actually install ROS - the issue I am having is with install-time dependencies.

**Comment by dirk-thomas** [comment]
@ANogin Thank you for reporting this quickly.

**Comment by mikepurvis** [comment]
Thanks for the quick fix. 🎉
