### ISSUE TITLE
All ros* commands disappear after apt-installing python3-rospkg

### ISSUE THREAD

**Issue by d4n1elchen** [ros-infrastructure/rospkg#203]
I tried to port my python2 scripts to python3. At the beginning, I got rospkg module missing and I install it by `apt install python3-rospkg`. Now everything else disappear. (rosrun, roslaunch, rosdep, etc., missing rospy module as well) Not sure what make this happen, could anyone help?

ROS distro: melodic (installed using apt install)
OS: Ubuntu 18.04

**Comment by dirk-thomas** [comment]
The Debian package `python-rospkg` and `python3-rospkg` are *not* side-by-side installable because they both provide the same global executables. I am sure `apt` showed a very specific warning that almost all installed ROS packages will be installed if you install `python3-rospkg`.

Instead you should only additionally install `python3-rospkg-modules` which can coexist with the Python 2 version of it.

Please ask questions like this in the future on answers.ros.org instead.
