### ISSUE TITLE
Get Path of Devel Space

### ISSUE THREAD

**Issue by mitchellwills** [ros-infrastructure/rospkg#79]
Right now there does not appear to be a way to access the devel space through rospkg. I have a situation where I want to locate some files that I build (and are installed to the devel space) that will also be installed to the install space when building in that configuration. However, when I am not building with install enabled rospkg resolves the package path to the original source directory. Is it possible to add an optional flag to get_path that would cause it to resolve to the package devel share path when not building with install enabled and the install share path when building with install enabled?

**Comment by dirk-thomas** [comment]
Since `rospkg` was designed in pre-catkin times it is not aware of the devel space.

You might want to call the tool `catkin_find` which will be able to find resources in the source space, devel space as well as install space. You can also call the Python API used by the script directly: https://github.com/ros/catkin/blob/6d9e3eb555ea8006294472ac6baa6b7cf0d7d273/python/catkin/find_in_workspaces.py#L90

**Comment by mitchellwills** [comment]
Oh awesome didn't realize that existed.
